var _ = require('./utils');
var interrupts = require('./interrupts');
var swym = require('./swym');
var load = require('./load');

var i = 0;
//0 stands for register, other numbers for the byte width of the argument, -1
//for unused byte
var $X_$Y_$Z = [0, 0, 0];
var $X_$Y_Z = [0, 0, 1];
var $X_Y_$Z = [0, 1, 0];
var $X_Y_Z = [0, 1, 1];
var $X_YZ = [0, 2];
var X_YZ = [1, 2];
var XYZ = [3];
var X_$Y_$Z = [1, 0, 0];
var X_$Y_Z = [1, 0, 1];
var $X_Z = [0, -1, 1];
var X_$Z = [1, -1, 0];
var X_Z = [1, -1, 1];
var $X_0 = [0, -1, -1];
var $Z = [-1, -1, 0];
var X_Y_Z = [1, 1, 1];
var niladic = [-1, -1, -1];

var opcodes = [
  //name, oops cost, mems cost, signature
  ['TRAP', 5, 0, X_Y_Z, interrupts.TRAP],
  ['FCMP', 1, 0, $X_$Y_$Z],
  ['FUN', 1, 0, $X_$Y_$Z],
  ['FEQL', 1, 0, $X_$Y_$Z],
  ['FADD', 4, 0, $X_$Y_$Z],
  ['FIX', 4, 0, $X_Y_$Z],
  ['FSUB', 4, 0, $X_$Y_$Z],
  ['FIXU', 4, 0, $X_Y_$Z],
  ['FLOT', 4, 0, $X_Y_$Z],
  ['FLOTI', 4, 0, $X_Y_Z],
  ['FLOTU', 4, 0, $X_Y_$Z],
  ['FLOTUI', 4, 0, $X_Y_Z],
  ['SFLOT', 4, 0, $X_Y_$Z],
  ['SFLOTI', 4, 0, $X_Y_Z],
  ['SFLOTU', 4, 0, $X_Y_$Z],
  ['SFLOTUI', 4, 0, $X_Y_Z],
  ['FMUL', 4, 0, $X_$Y_$Z],
  ['FCMPE', 4, 0, $X_$Y_$Z],
  ['FUNE', 1, 0, $X_$Y_$Z],
  ['FEQLE', 4, 0, $X_$Y_$Z],
  ['FDIV', 40, 0, $X_$Y_$Z],
  ['FSQRT', 40, 0, $X_Y_$Z],
  ['FREM', 4, 0, $X_$Y_$Z],
  ['FINT', 4, 0, $X_Y_$Z],
  ['MUL', 10, 0, $X_$Y_$Z],
  ['MULI', 10, 0, $X_$Y_Z],
  ['MULU', 10, 0, $X_$Y_$Z],
  ['MULUI', 10, 0, $X_$Y_Z],
  ['DIV', 60, 0, $X_$Y_$Z],
  ['DIVI', 60, 0, $X_$Y_Z],
  ['DIVU', 60, 0, $X_$Y_$Z],
  ['DIVUI', 60, 0, $X_$Y_Z],
  ['ADD', 1, 0, $X_$Y_$Z],
  ['ADDI', 1, 0, $X_$Y_Z],
  ['ADDU', 1, 0, $X_$Y_$Z],
  ['ADDUI', 1, 0, $X_$Y_Z],
  ['SUB', 1, 0, $X_$Y_$Z],
  ['SUBI', 1, 0, $X_$Y_Z],
  ['SUBU', 1, 0, $X_$Y_$Z],
  ['SUBUI', 1, 0, $X_$Y_Z],
  ['2ADDU', 1, 0, $X_$Y_$Z],
  ['2ADDUI', 1, 0, $X_$Y_Z],
  ['4ADDU', 1, 0, $X_$Y_$Z],
  ['4ADDUI', 1, 0, $X_$Y_Z],
  ['8ADDU', 1, 0, $X_$Y_$Z],
  ['8ADDUI', 1, 0, $X_$Y_Z],
  ['16ADDU', 1, 0, $X_$Y_$Z],
  ['16ADDUI', 1, 0, $X_$Y_Z],
  ['CMP', 1, 0, $X_$Y_$Z],
  ['CMPI', 1, 0, $X_$Y_Z],
  ['CMPU', 1, 0, $X_$Y_$Z],
  ['CMPUI', 1, 0, $X_$Y_Z],
  ['NEG', 1, 0, $X_Y_$Z],
  ['NEGI', 1, 0, $X_Y_Z],
  ['NEGU', 1, 0, $X_Y_$Z],
  ['NEGUI', 1, 0, $X_Y_Z],
  ['SL', 1, 0, $X_$Y_$Z],
  ['SLI', 1, 0, $X_$Y_Z],
  ['SLU', 1, 0, $X_$Y_$Z],
  ['SLUI', 1, 0, $X_$Y_Z],
  ['SR', 1, 0, $X_$Y_$Z],
  ['SRI', 1, 0, $X_$Y_Z],
  ['SRU', 1, 0, $X_$Y_$Z],
  ['SRUI', 1, 0, $X_$Y_Z],
  //actual cost of branching operations depends on whether the branch is taken
  ['BN', 1, 0, $X_YZ],
  ['BNB', 1, 0, $X_YZ],
  ['BZ', 1, 0, $X_YZ],
  ['BZB', 1, 0, $X_YZ],
  ['BP', 1, 0, $X_YZ],
  ['BPB', 1, 0, $X_YZ],
  ['BOD', 1, 0, $X_YZ],
  ['BODB', 1, 0, $X_YZ],
  ['BNN', 1, 0, $X_YZ],
  ['BNNB', 1, 0, $X_YZ],
  ['BNZ', 1, 0, $X_YZ],
  ['BNZB', 1, 0, $X_YZ],
  ['BNP', 1, 0, $X_YZ],
  ['BNPB', 1, 0, $X_YZ],
  ['BEV', 1, 0, $X_YZ],
  ['BEVB', 1, 0, $X_YZ],
  ['PBN', 1, 0, $X_YZ],
  ['PBNB', 1, 0, $X_YZ],
  ['PBZ', 1, 0, $X_YZ],
  ['PBZB', 1, 0, $X_YZ],
  ['PBP', 1, 0, $X_YZ],
  ['PBPB', 1, 0, $X_YZ],
  ['PBOD', 1, 0, $X_YZ],
  ['PBODB', 1, 0, $X_YZ],
  ['PBNN', 1, 0, $X_YZ],
  ['PBNNB', 1, 0, $X_YZ],
  ['PBNZ', 1, 0, $X_YZ],
  ['PBNZB', 1, 0, $X_YZ],
  ['PBNP', 1, 0, $X_YZ],
  ['PBNPZ', 1, 0, $X_YZ],
  ['PBEV', 1, 0, $X_YZ],
  ['PBEVB', 1, 0, $X_YZ],
  ['CSN', 1, 0, $X_$Y_$Z],
  ['CSNI', 1, 0, $X_$Y_Z],
  ['CSZ', 1, 0, $X_$Y_$Z],
  ['CSZI', 1, 0, $X_$Y_Z],
  ['CSP', 1, 0, $X_$Y_$Z],
  ['CSPI', 1, 0, $X_$Y_Z],
  ['CSOD', 1, 0, $X_$Y_$Z],
  ['CSODI', 1, 0, $X_$Y_Z],
  ['CSNN', 1, 0, $X_$Y_$Z],
  ['CSNNI', 1, 0, $X_$Y_Z],
  ['CSNZ', 1, 0, $X_$Y_$Z],
  ['CSNZI', 1, 0, $X_$Y_Z],
  ['CSNP', 1, 0, $X_$Y_$Z],
  ['CSNPI', 1, 0, $X_$Y_Z],
  ['CSEV', 1, 0, $X_$Y_$Z],
  ['CSEVI', 1, 0, $X_$Y_Z],
  ['ZSN', 1, 0, $X_$Y_$Z],
  ['ZSNI', 1, 0, $X_$Y_Z],
  ['ZSZ', 1, 0, $X_$Y_$Z],
  ['ZSZI', 1, 0, $X_$Y_Z],
  ['ZSP', 1, 0, $X_$Y_$Z],
  ['ZSPI', 1, 0, $X_$Y_Z],
  ['ZSOD', 1, 0, $X_$Y_$Z],
  ['ZSODI', 1, 0, $X_$Y_Z],
  ['ZSNN', 1, 0, $X_$Y_$Z],
  ['ZSNNI', 1, 0, $X_$Y_Z],
  ['ZSNZ', 1, 0, $X_$Y_$Z],
  ['ZSNZI', 1, 0, $X_$Y_Z],
  ['ZSNP', 1, 0, $X_$Y_$Z],
  ['ZSNPI', 1, 0, $X_$Y_Z],
  ['ZSEV', 1, 0, $X_$Y_$Z],
  ['ZSEVI', 1, 0, $X_$Y_Z],
  ['LDB', 1, 1, $X_$Y_$Z, load.LDB],
  ['LDBI', 1, 1, $X_$Y_Z, load.LDBI],
  ['LDBU', 1, 1, $X_$Y_$Z, load.LDBU],
  ['LDBUI', 1, 1, $X_$Y_Z, load.LDBUI],
  ['LDW', 1, 1, $X_$Y_$Z, load.LDW],
  ['LDWI', 1, 1, $X_$Y_Z, load.LDWI],
  ['LDWU', 1, 1, $X_$Y_$Z, load.LDWU],
  ['LDWUI', 1, 1, $X_$Y_Z, load.LDWUI],
  ['LDT', 1, 1, $X_$Y_$Z, load.LDT],
  ['LDTI', 1, 1, $X_$Y_Z, load.LDTI],
  ['LDTU', 1, 1, $X_$Y_$Z, load.LDTU],
  ['LDTUI', 1, 1, $X_$Y_Z, load.LDTUI],
  ['LDO', 1, 1, $X_$Y_$Z, load.LDO],
  ['LDOI', 1, 1, $X_$Y_Z, load.LDOI],
  ['LDOU', 1, 1, $X_$Y_$Z, load.LDOU],
  ['LDOUI', 1, 1, $X_$Y_Z, load.LDOUI],
  ['LDSF', 1, 1, $X_$Y_$Z],
  ['LDSFI', 1, 1, $X_$Y_$Z],
  ['LDHT', 1, 1, $X_$Y_$Z, load.LDHT],
  ['LDHTI', 1, 1, $X_$Y_Z, load.LDHTI],
  ['CSWAP', 2, 2, $X_$Y_$Z],
  ['CSWAPI', 2, 2, $X_$Y_Z],
  ['LDUNC', 1, 1, $X_$Y_$Z],
  ['LDUNCI', 1, 1, $X_$Y_Z],
  ['LDVTS', 1, 0, $X_$Y_$Z],
  ['LDVTSI', 1, 0, $X_$Y_Z],
  ['PRELD', 1, 0, X_$Y_$Z],
  ['PRELDI', 1, 0, X_$Y_Z],
  ['PREGO', 1, 0, X_$Y_$Z],
  ['PREGOI', 1, 0, X_$Y_Z],
  ['GO', 1, 0, $X_$Y_$Z],
  ['GOI', 1, 0, $X_$Y_Z],
  ['STB', 1, 1, $X_$Y_$Z],
  ['STBI', 1, 1, $X_$Y_Z],
  ['STBU', 1, 1,  $X_$Y_$Z],
  ['STBUI', 1, 1, $X_$Y_Z],
  ['STW', 1, 1,  $X_$Y_$Z],
  ['STWI', 1, 1, $X_$Y_Z],
  ['STWU', 1, 1,  $X_$Y_$Z],
  ['STWUI', 1, 1, $X_$Y_Z],
  ['STT', 1, 1,  $X_$Y_$Z],
  ['STTI', 1, 1, $X_$Y_Z],
  ['STTU', 1, 1,  $X_$Y_$Z],
  ['STTUI', 1, 1, $X_$Y_Z],
  ['STO', 1, 1,  $X_$Y_$Z],
  ['STOI', 1, 1, $X_$Y_Z],
  ['STOU', 1, 1,  $X_$Y_$Z],
  ['STOUI', 1, 1, $X_$Y_Z],
  ['STSF', 1, 1, $X_$Y_$Z],
  ['STSFI', 1, 1,  $X_$Y_Z],
  ['STHT', 1, 1, $X_$Y_$Z],
  ['STHTI', 1, 1, $X_$Y_Z],
  ['STCO', 1, 1, $X_$Y_$Z],
  ['STCOI', 1, 1, $X_$Y_Z],
  ['STUNC', 1, 1, $X_$Y_$Z],
  ['STUNCI', 1, 1, $X_$Y_Z],
  ['SYNCD', 1, 0, X_$Y_$Z],
  ['SYNCDI', 1, 0, X_$Y_Z],
  ['PREST', 1, 0, X_$Y_$Z],
  ['PRESTI', 1, 0, X_$Y_Z],
  ['SYNCID', 1, 0, X_$Y_$Z],
  ['SYNCIDI', 1, 0, X_$Y_Z],
  ['PUSHGO', 3, 0, $X_$Y_$Z],
  ['PUSHGOI', 3, 0, $X_$Y_Z],
  ['OR', 1, 0, $X_$Y_$Z],
  ['ORI', 1, 0, $X_$Y_Z],
  ['ORN', 1, 0, $X_$Y_$Z],
  ['ORNI', 1, 0, $X_$Y_Z],
  ['NOR', 1, 0, $X_$Y_$Z],
  ['NORI', 1, 0, $X_$Y_Z],
  ['XOR', 1, 0, $X_$Y_$Z],
  ['XORI', 1, 0, $X_$Y_Z],
  ['AND', 1, 0, $X_$Y_$Z],
  ['ANDI', 1, 0, $X_$Y_Z],
  ['ANDN', 1, 0, $X_$Y_$Z],
  ['ANDNI', 1, 0, $X_$Y_Z],
  ['NAND', 1, 0, $X_$Y_$Z],
  ['NANDI', 1, 0, $X_$Y_Z],
  ['NXOR', 1, 0, $X_$Y_$Z],
  ['NXORI', 1, 0, $X_$Y_Z],
  ['BDIF', 1, 0, $X_$Y_$Z],
  ['BDIFI', 1, 0, $X_$Y_Z],
  ['WDIF', 1, 0, $X_$Y_$Z],
  ['WDIFI', 1, 0, $X_$Y_Z],
  ['TDIF', 1, 0, $X_$Y_$Z],
  ['TDIFI', 1, 0, $X_$Y_Z],
  ['ODIF', 1, 0, $X_$Y_$Z],
  ['ODIFI', 1, 0, $X_$Y_Z],
  ['MUX', 1, 0, $X_$Y_$Z],
  ['MUXI', 1, 0, $X_$Y_Z],
  ['SADD', 1, 0, $X_$Y_$Z],
  ['SADDI', 1, 0, $X_$Y_Z],
  ['MOR', 1, 0, $X_$Y_$Z],
  ['MORI', 1, 0, $X_$Y_Z],
  ['MXOR', 1, 0, $X_$Y_$Z],
  ['MXORI', 1, 0, $X_$Y_Z],
  ['SETH', 1, 0, $X_YZ],
  ['SETMH', 1, 0, $X_YZ],
  ['SETML', 1, 0, $X_YZ],
  ['SETL', 1, 0, $X_YZ],
  ['INCH', 1, 0, $X_YZ],
  ['INCMH', 1, 0, $X_YZ],
  ['INCML', 1, 0, $X_YZ],
  ['INCL', 1, 0, $X_YZ],
  ['ORH', 1, 0, $X_YZ],
  ['ORMH', 1, 0, $X_YZ],
  ['ORML', 1, 0, $X_YZ],
  ['ORL', 1, 0, $X_YZ],
  ['ANDNH', 1, 0, $X_YZ],
  ['ANDNMH', 1, 0, $X_YZ],
  ['ANDNML', 1, 0, $X_YZ],
  ['ANDNL', 1, 0, $X_YZ],
  ['JMP', 1, 0, XYZ],
  ['JMPB', 1, 0, XYZ],
  ['PUSHJ', 1, 0, $X_YZ],
  ['PUSHJB', 1, 0, $X_YZ],
  ['GETA', 1, 0, $X_YZ],
  ['GETAB', 1, 0, $X_YZ],
  ['PUT', 1, 0, X_$Z],
  ['PUTI', 1, 0, X_Z],
  ['POP', 3, 0, X_YZ],
  ['RESUME', 5, 0, niladic, interrupts.RESUME],
  ['SAVE', 1, 20, $X_0],
  ['UNSAVE', 1, 20, $Z],
  ['SYNC', 1, 0, XYZ],
  ['SWYM', 1, 0, XYZ, swym],
  ['GET', 1, 0, $X_Z],
  ['TRIP', 5, 0, X_Y_Z, interrupts.TRIP],
];

exports.opnames = opcodes.reduce(function(memo, op, index) {
  var key = _.hexifyByte(index);
  memo[key] = op[0];
  return memo;
}, {});

exports.opcodes = opcodes.reduce(function(memo, op, index) {
  memo[op[0]] = index;
  return memo;
}, {});

exports.formats = opcodes.reduce(function(memo, op) {
  memo[op[0]] = op[3];
  return memo;
}, {});

exports.costs = opcodes.reduce(function(memo, op, index) {
  var key = _.hexifyByte(index);
  memo[key] = {oops: op[1], mems: op[2]};
  return memo;
}, {});

exports.ops = opcodes.map(function(o) {
  return o[4];
});
